// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KNaming.proto

package knaming

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////////////////////////////////////
//
//                              KNamingNotify
//
////////////////////////////////////////////////////////////////////////////////
type KNamingInfo struct {
	Service              *string  `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	State                *uint32  `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	Object               *string  `protobuf:"bytes,3,opt,name=object" json:"object,omitempty"`
	Domain               *string  `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
	Protocol             *string  `protobuf:"bytes,5,opt,name=protocol" json:"protocol,omitempty"`
	Priority             *uint32  `protobuf:"varint,11,opt,name=priority" json:"priority,omitempty"`
	Endpoint             *string  `protobuf:"bytes,12,opt,name=endpoint" json:"endpoint,omitempty"`
	Stateless            *bool    `protobuf:"varint,13,opt,name=stateless" json:"stateless,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KNamingInfo) Reset()         { *m = KNamingInfo{} }
func (m *KNamingInfo) String() string { return proto.CompactTextString(m) }
func (*KNamingInfo) ProtoMessage()    {}
func (*KNamingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec53dccc46b3dc0, []int{0}
}

func (m *KNamingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KNamingInfo.Unmarshal(m, b)
}
func (m *KNamingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KNamingInfo.Marshal(b, m, deterministic)
}
func (m *KNamingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KNamingInfo.Merge(m, src)
}
func (m *KNamingInfo) XXX_Size() int {
	return xxx_messageInfo_KNamingInfo.Size(m)
}
func (m *KNamingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KNamingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KNamingInfo proto.InternalMessageInfo

func (m *KNamingInfo) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *KNamingInfo) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *KNamingInfo) GetObject() string {
	if m != nil && m.Object != nil {
		return *m.Object
	}
	return ""
}

func (m *KNamingInfo) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *KNamingInfo) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *KNamingInfo) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *KNamingInfo) GetEndpoint() string {
	if m != nil && m.Endpoint != nil {
		return *m.Endpoint
	}
	return ""
}

func (m *KNamingInfo) GetStateless() bool {
	if m != nil && m.Stateless != nil {
		return *m.Stateless
	}
	return false
}

type KNamingNotify struct {
	Sign                 *uint32        `protobuf:"varint,1,req,name=sign" json:"sign,omitempty"`
	NameList             []*KNamingInfo `protobuf:"bytes,2,rep,name=nameList" json:"nameList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KNamingNotify) Reset()         { *m = KNamingNotify{} }
func (m *KNamingNotify) String() string { return proto.CompactTextString(m) }
func (*KNamingNotify) ProtoMessage()    {}
func (*KNamingNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec53dccc46b3dc0, []int{1}
}

func (m *KNamingNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KNamingNotify.Unmarshal(m, b)
}
func (m *KNamingNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KNamingNotify.Marshal(b, m, deterministic)
}
func (m *KNamingNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KNamingNotify.Merge(m, src)
}
func (m *KNamingNotify) XXX_Size() int {
	return xxx_messageInfo_KNamingNotify.Size(m)
}
func (m *KNamingNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_KNamingNotify.DiscardUnknown(m)
}

var xxx_messageInfo_KNamingNotify proto.InternalMessageInfo

func (m *KNamingNotify) GetSign() uint32 {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return 0
}

func (m *KNamingNotify) GetNameList() []*KNamingInfo {
	if m != nil {
		return m.NameList
	}
	return nil
}

////////////////////////////////////////////////////////////////////////////////
//
//                              KNamingDump
//
////////////////////////////////////////////////////////////////////////////////
type KNamingObjectInfo struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Endpoint             *string  `protobuf:"bytes,2,req,name=endpoint" json:"endpoint,omitempty"`
	Priority             *uint32  `protobuf:"varint,3,req,name=priority" json:"priority,omitempty"`
	Hits                 *uint32  `protobuf:"varint,4,req,name=hits" json:"hits,omitempty"`
	State                *uint32  `protobuf:"varint,5,req,name=state" json:"state,omitempty"`
	Endpoint2            *string  `protobuf:"bytes,10,opt,name=endpoint2" json:"endpoint2,omitempty"`
	Hits2                *uint32  `protobuf:"varint,11,opt,name=hits2" json:"hits2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KNamingObjectInfo) Reset()         { *m = KNamingObjectInfo{} }
func (m *KNamingObjectInfo) String() string { return proto.CompactTextString(m) }
func (*KNamingObjectInfo) ProtoMessage()    {}
func (*KNamingObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec53dccc46b3dc0, []int{2}
}

func (m *KNamingObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KNamingObjectInfo.Unmarshal(m, b)
}
func (m *KNamingObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KNamingObjectInfo.Marshal(b, m, deterministic)
}
func (m *KNamingObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KNamingObjectInfo.Merge(m, src)
}
func (m *KNamingObjectInfo) XXX_Size() int {
	return xxx_messageInfo_KNamingObjectInfo.Size(m)
}
func (m *KNamingObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KNamingObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KNamingObjectInfo proto.InternalMessageInfo

func (m *KNamingObjectInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *KNamingObjectInfo) GetEndpoint() string {
	if m != nil && m.Endpoint != nil {
		return *m.Endpoint
	}
	return ""
}

func (m *KNamingObjectInfo) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *KNamingObjectInfo) GetHits() uint32 {
	if m != nil && m.Hits != nil {
		return *m.Hits
	}
	return 0
}

func (m *KNamingObjectInfo) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *KNamingObjectInfo) GetEndpoint2() string {
	if m != nil && m.Endpoint2 != nil {
		return *m.Endpoint2
	}
	return ""
}

func (m *KNamingObjectInfo) GetHits2() uint32 {
	if m != nil && m.Hits2 != nil {
		return *m.Hits2
	}
	return 0
}

type KNamingServiceInfo struct {
	Service              *string              `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	Domain               *string              `protobuf:"bytes,2,req,name=domain" json:"domain,omitempty"`
	Protocol             *string              `protobuf:"bytes,3,req,name=protocol" json:"protocol,omitempty"`
	Stateless            *bool                `protobuf:"varint,4,req,name=stateless" json:"stateless,omitempty"`
	Recommands           []string             `protobuf:"bytes,5,rep,name=recommands" json:"recommands,omitempty"`
	Objects              []*KNamingObjectInfo `protobuf:"bytes,6,rep,name=objects" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *KNamingServiceInfo) Reset()         { *m = KNamingServiceInfo{} }
func (m *KNamingServiceInfo) String() string { return proto.CompactTextString(m) }
func (*KNamingServiceInfo) ProtoMessage()    {}
func (*KNamingServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec53dccc46b3dc0, []int{3}
}

func (m *KNamingServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KNamingServiceInfo.Unmarshal(m, b)
}
func (m *KNamingServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KNamingServiceInfo.Marshal(b, m, deterministic)
}
func (m *KNamingServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KNamingServiceInfo.Merge(m, src)
}
func (m *KNamingServiceInfo) XXX_Size() int {
	return xxx_messageInfo_KNamingServiceInfo.Size(m)
}
func (m *KNamingServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KNamingServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KNamingServiceInfo proto.InternalMessageInfo

func (m *KNamingServiceInfo) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *KNamingServiceInfo) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *KNamingServiceInfo) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *KNamingServiceInfo) GetStateless() bool {
	if m != nil && m.Stateless != nil {
		return *m.Stateless
	}
	return false
}

func (m *KNamingServiceInfo) GetRecommands() []string {
	if m != nil {
		return m.Recommands
	}
	return nil
}

func (m *KNamingServiceInfo) GetObjects() []*KNamingObjectInfo {
	if m != nil {
		return m.Objects
	}
	return nil
}

type KNamingDump struct {
	Service              []*KNamingServiceInfo `protobuf:"bytes,1,rep,name=service" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *KNamingDump) Reset()         { *m = KNamingDump{} }
func (m *KNamingDump) String() string { return proto.CompactTextString(m) }
func (*KNamingDump) ProtoMessage()    {}
func (*KNamingDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec53dccc46b3dc0, []int{4}
}

func (m *KNamingDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KNamingDump.Unmarshal(m, b)
}
func (m *KNamingDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KNamingDump.Marshal(b, m, deterministic)
}
func (m *KNamingDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KNamingDump.Merge(m, src)
}
func (m *KNamingDump) XXX_Size() int {
	return xxx_messageInfo_KNamingDump.Size(m)
}
func (m *KNamingDump) XXX_DiscardUnknown() {
	xxx_messageInfo_KNamingDump.DiscardUnknown(m)
}

var xxx_messageInfo_KNamingDump proto.InternalMessageInfo

func (m *KNamingDump) GetService() []*KNamingServiceInfo {
	if m != nil {
		return m.Service
	}
	return nil
}

func init() {
	proto.RegisterType((*KNamingInfo)(nil), "knaming.KNamingInfo")
	proto.RegisterType((*KNamingNotify)(nil), "knaming.KNamingNotify")
	proto.RegisterType((*KNamingObjectInfo)(nil), "knaming.KNamingObjectInfo")
	proto.RegisterType((*KNamingServiceInfo)(nil), "knaming.KNamingServiceInfo")
	proto.RegisterType((*KNamingDump)(nil), "knaming.KNamingDump")
}

func init() { proto.RegisterFile("KNaming.proto", fileDescriptor_5ec53dccc46b3dc0) }

var fileDescriptor_5ec53dccc46b3dc0 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcb, 0x6a, 0xe3, 0x30,
	0x14, 0xc5, 0xaf, 0x24, 0xbe, 0x19, 0x2f, 0xe6, 0x12, 0x06, 0x91, 0x09, 0x83, 0xf1, 0xca, 0xab,
	0x30, 0x84, 0x99, 0x3f, 0xc8, 0xa6, 0xb4, 0xa4, 0xa0, 0xd2, 0x0f, 0x70, 0x1d, 0x25, 0x55, 0x1b,
	0x4b, 0xc1, 0x52, 0x0b, 0xf9, 0xb8, 0xfe, 0x46, 0xb7, 0xfd, 0x95, 0x22, 0xc9, 0xaf, 0x84, 0x42,
	0x77, 0x3a, 0xe7, 0x4a, 0x97, 0xf3, 0x10, 0x24, 0xd7, 0x9b, 0xa2, 0xe2, 0x62, 0xbf, 0x3c, 0xd6,
	0x52, 0x4b, 0x1c, 0x3f, 0x0b, 0x0b, 0xb3, 0x0f, 0x0f, 0xa6, 0xcd, 0xe8, 0x4a, 0xec, 0x24, 0x12,
	0x18, 0x2b, 0x56, 0xbf, 0xf2, 0x92, 0x11, 0x2f, 0xf5, 0xf3, 0x98, 0xb6, 0x10, 0x67, 0x10, 0x29,
	0x5d, 0x68, 0x46, 0xfc, 0xd4, 0xcf, 0x13, 0xea, 0x00, 0xfe, 0x82, 0x91, 0x7c, 0x78, 0x62, 0xa5,
	0x26, 0x41, 0xea, 0xe5, 0x31, 0x6d, 0x90, 0xe1, 0xb7, 0xb2, 0x2a, 0xb8, 0x20, 0xa1, 0xe3, 0x1d,
	0xc2, 0x39, 0x4c, 0xac, 0x82, 0x52, 0x1e, 0x48, 0x64, 0x27, 0x1d, 0x76, 0x33, 0x2e, 0x6b, 0xae,
	0x4f, 0x64, 0x9a, 0x7a, 0x79, 0x42, 0x3b, 0x6c, 0x66, 0x4c, 0x6c, 0x8f, 0x92, 0x0b, 0x4d, 0x7e,
	0xb8, 0x77, 0x2d, 0xc6, 0x05, 0xc4, 0x56, 0xcc, 0x81, 0x29, 0x45, 0x92, 0xd4, 0xcb, 0x27, 0xb4,
	0x27, 0xb2, 0xfb, 0xce, 0xfb, 0x46, 0x6a, 0xbe, 0x3b, 0x21, 0x42, 0xa8, 0xf8, 0x5e, 0x58, 0x7f,
	0x09, 0xb5, 0x67, 0xfc, 0x0b, 0x13, 0x51, 0x54, 0xec, 0x86, 0x2b, 0x4d, 0xfc, 0x34, 0xc8, 0xa7,
	0xab, 0xd9, 0xb2, 0x89, 0x68, 0x39, 0x88, 0x87, 0x76, 0xb7, 0xb2, 0x37, 0x0f, 0x7e, 0x36, 0x93,
	0x5b, 0x6b, 0xd9, 0xc6, 0x87, 0x10, 0x9a, 0x1b, 0x4d, 0x76, 0xf6, 0x7c, 0x26, 0xdd, 0xb7, 0x7c,
	0x2f, 0x7d, 0x68, 0x39, 0xb0, 0x7a, 0x7a, 0xcb, 0x08, 0xe1, 0x23, 0xd7, 0x8a, 0x84, 0x4e, 0xa7,
	0x39, 0xf7, 0x25, 0x44, 0xc3, 0x12, 0x16, 0x10, 0xb7, 0x1b, 0x57, 0x04, 0x6c, 0x3a, 0x3d, 0x61,
	0xde, 0x98, 0xb7, 0xab, 0x26, 0x53, 0x07, 0xb2, 0x77, 0x0f, 0xb0, 0xd1, 0x7f, 0xe7, 0x1a, 0xfe,
	0xa6, 0xff, 0xbe, 0x51, 0x67, 0xe2, 0xab, 0x46, 0x03, 0x67, 0xaf, 0x6b, 0xf4, 0xac, 0x19, 0xe3,
	0x63, 0xd8, 0x0c, 0xfe, 0x01, 0xa8, 0x59, 0x29, 0xab, 0xaa, 0x10, 0x5b, 0x45, 0xa2, 0x34, 0xc8,
	0x63, 0x3a, 0x60, 0xf0, 0x1f, 0x8c, 0xdd, 0x6f, 0x52, 0x64, 0x64, 0x3b, 0x99, 0x5f, 0x76, 0xd2,
	0x27, 0x4f, 0xdb, 0xab, 0xd9, 0xba, 0xfb, 0xd0, 0xeb, 0x97, 0xea, 0x88, 0xff, 0x87, 0x86, 0xcc,
	0x92, 0xdf, 0x97, 0x4b, 0x06, 0xf6, 0x3b, 0xb7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xf0,
	0x30, 0x27, 0x30, 0x03, 0x00, 0x00,
}
